// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgiracgxmctotfljrmkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnaXJhY2d4bWN0b3RmbGpybWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTk4NjQsImV4cCI6MjA2MzI3NTg2NH0.FAeYGRo-ALWsFOb7H-IS9ctcmKRzoGk85eFxgB4iuvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);